### ISSUE TITLE
Gif is sometimes bigger then the color box

### ISSUE THREAD

**Issue by kajmaj87** [Kondziela/meme-retro#2]
Please fix ASAP, I need this for work.

![image](https://user-images.githubusercontent.com/1036795/53725444-4ebe5f80-3e6c-11e9-99ad-375eee7a91fc.png)

**Comment by Morpheus1993** [comment]
Created a bug to fix this issue.

**Comment by jaszka** [comment]
Hello @kajmaj87 ,

We're happy to announce that the bug is fixed in the new version of our API. Thank you for your thorough testing.

Have a nice day!

Best,
jaszka
